#!/bin/bash

EWW_BIN="/usr/bin/eww"
MON=$(hyprctl activewindow -j | jq -r '.monitor')

calendar() {
LOCK_FILE="$HOME/.cache/eww-calendar.lock"

run() {
    ${EWW_BIN} open --screen "$MON" calendar
}

# Open widgets
if [[ ! -f "$LOCK_FILE" ]]; then
    # ${EWW_BIN} close system player_win audio_ctl
    touch "$LOCK_FILE"
    run && echo "ok good!"
else
    ${EWW_BIN} close calendar
    rm "$LOCK_FILE" && echo "closed"
fi
}


system() {
LOCK_FILE_MEM="$HOME/.cache/eww-system.lock"

run() {
    ${EWW_BIN} open system
}

# Open widgets
if [[ ! -f "$LOCK_FILE_MEM" ]]; then
    ${EWW_BIN} close calendar player_win audio_ctl
    touch "$LOCK_FILE_MEM"
    run && echo "ok good!"
else
    ${EWW_BIN} close system
    rm "$LOCK_FILE_MEM" && echo "closed"
fi
}


player() {
LOCK_FILE_SONG="$HOME/.cache/eww-song.lock"

run() {
    ${EWW_BIN} open --screen "$MON" player_win
}

# Open widgets
if [[ ! -f "$LOCK_FILE_SONG" ]]; then
    ${EWW_BIN} close system calendar
    touch "$LOCK_FILE_SONG"
    run && echo "ok good!"
else
    ${EWW_BIN} close player_win
    rm "$LOCK_FILE_SONG" && echo "closed"
fi
}



audio() {
LOCK_FILE_AUDIO="$HOME/.cache/eww-audio.lock"
EWW_BIN="$HOME/.local/bin/eww/eww"

run() {
    ${EWW_BIN} open audio_ctl
}

# Open widgets
if [[ ! -f "$LOCK_FILE_AUDIO" ]]; then
    ${EWW_BIN} close system calendar player
    touch "$LOCK_FILE_AUDIO"
    run && echo "ok good!"
else
    ${EWW_BIN} close audio_ctl
    rm "$LOCK_FILE_AUDIO" && echo "closed"
fi
}


if [ "$1" = "calendar" ]; then
calendar
elif [ "$1" = "system" ]; then
system
elif [ "$1" = "player" ]; then
player
elif [ "$1" = "audio" ]; then
audio
fi
